word_list = [["abyss", "a deep or seemingly bottomless chasm"],
             ["ardvark","also known as African ant bear"],
             ["askew", "not in a straight or level position"],
             ["awkward", "causing or feeling uneasy embarrassment or inconvenience"],
             ["baboon", "there once was a brainy ........"],
             ["beekeeper", "a person who owns and breeds bees, especially for their honey"],
             ["blizzard", "a severe snowstorm with high winds"],
             ["bookworm", "a person who enjoys reading"],
             ["buffalo", "a heavily built wild ox with backswept horns, found mainly in the Old World tropics"],
             ["caliph", "Arabic word meaning 'successor' or 'next in line'"],
             ["camel", "animal with a hump"],
             ["croquet", "a game played on a lawn, in which wooden balls are driven through a series of square-topped hoops by means of mallets"],
             ["duplex", "a house with two units sharing a common wall"],
             ["dwarves", "a member of a mythical race of short, stocky humanlike creatures who are generally skilled in mining and metalworking"],
             ["embezzle", "steal or misappropriate (money placed in one's trust or belonging to the organization for which one works)"],
             ["espionage", "the practice of spying or of using spies, typically by governments to obtain political and military information"],
             ["fishhook", "a usually barbed hook for catching fish"],
             ["fuchsia", "a shrub with pendulous tubular flowers that are typically of two contrasting colours, native to America and New Zealand and are commonly grown as ornamentals"],
             ["galvanize", "shock or excite (someone) into taking action"],
             ["gazebo", "a small building, especially one in the garden of a house, that gives a wide view of the surrounding area"],
             ["glowworm", "a soft-bodied beetle with luminescent organs in the abdomen"],
             ["glyph", "a hieroglyphic character or symbol"],
             ["gossip", "casual or unconstrained conversation or reports about other people, typically involving details that are not confirmed as being true"],
             ["haphazard", "lacking any obvious principle of organization"],
             ["injury", "damage to a person's feelings"],
             ["ivory", "the tusks of an elephant"],
             ["ivy", "a woody evergreen Eurasian climbing plant, typically having shiny, dark green five-pointed leaves"],
             ["jaundice", "a medical condition with yellowing of the skin"],
             ["jaywalk", "to cross a street carelessly or in an illegal manner so as to be endangered by traffic"],
             ["jinx", "a person or thing that brings bad luck"],
             ["jockey", "a person who rides in horse races, especially as a profession"],
             ["jogging", "the activity of running at a steady, gentle pace as a form of physical exercise"],
             ["joyful", "feeling, expressing, or causing great pleasure and happiness"],
             ["jukebox", "a machine that automatically plays a selected musical recording when a coin is inserted"],
             ["kayak", "a canoe of a type made of a light frame with a watertight covering having a small opening in the top to sit in"],
             ["kilobyte", "a unit of memory or data equal to 1,024 bytes"],
             ["kiwifruit", "a fruit with a thin hairy skin, green flesh, and black seeds"],
             ["larynx", "the voice box"],
             ["luxury", "a state of great comfort or elegance, especially when involving great expense"],
             ["microwave", "a small oven that cooks or heats food very quickly"],
             ["nightclub", "a place of entertainment open in the evening and usually serving food and liquor, having a floor show, and providing music for dancing"],
             ["oxygen", "we breath ....."],
             ["pajama", "any clothing suitable for wearing in bed"],
             ["peekaboo", "a game played with a young child, which involves hiding and suddenly reappearing"],
             ["pneumonia", "a form of acute respiratory infection that affects the lungs"],
             ["puppy", "a young dog"],
             ["queue", "a line or sequence of people or vehicles awaiting their turn to be attended to or to proceed"],
             ["rhythm", "a strong, regular repeated pattern of movement or sound"],
             ["rickshaw", "a light two-wheeled passenger vehicle drawn by one or more people"],
             ["scratch", "mark the surface of (something) with a sharp or pointed object"],
             ["strength", "the quality or state of being physically strong"],
             ["subway", "an underground railway"],
             ["thriftless", "spending money in an extravagant and wasteful way"],
             ["topaz", "a precious stone, typically colourless, yellow, or pale blue, consisting of an aluminium silicate that contains fluorine"],
             ["transcript", "a written, printed, or typed copy"],
             ["unknown", "not known"],
             ["vaporize", "convert or be converted into vapour"],
             ["vixen", "a female fox"],
             ["vodka", "an alcoholic spirit of Russian origin made by distillation of rye, wheat, or potatoes"],
             ["voodoo", "a religion that is based on African ancestor worship and practiced chiefly in Haiti"],
             ["wave", "a long body of water curling into an arched form and breaking on the shore"],
             ["whiskey", "a spirit distilled from malted grain, especially barley or rye"],
             ["witchcraft", "the practice of magic, especially for evil purposes"],
             ["wizard", "(in legends and fairy tales) a man who has magical powers"],
             ["wristwatch", "a watch worn on a strap round the wrist"],
             ["xylophone", "a musical instrument played by striking a row of wooden bars of graduated length with one or more small wooden or plastic beaters"],
             ["youthful", "young or seeming young"],
             ["yummy", "delicious"],
             ["zigzag", "a line or course having abrupt alternate right and left turns"],
             ["zipper", "commonly used device for binding together two edges of fabric or other flexible material"], ["zombie", "(in stories) a frightening creature that is a dead person who has been brought back to life, but without human qualities"]]
